version: "3.8"

# In this Docker Compose example, we only fire up the services required for local development.
# This is not advised for production use as it exposes ports to the database insecurely.
# If you're looking for a production-ready Docker Compose file, check out the `traefik.yml` file.

services:
  # Chrome Browser (for printing and previews)
  chrome:
    image: browserless/chrome:1.61.0-puppeteer-21.4.1
    restart: unless-stopped
    ports:
      - ${CHROME_PORT:-8080}:3000
    environment:
      KEEP_ALIVE: true
      CONNECTION_TIMEOUT: 10000
      EXIT_ON_HEALTH_FAILURE: true
      PRE_REQUEST_HEALTH_CHECK: true
      TOKEN: ${CHROME_TOKEN:-chrome_token}

  # Redis (for cache & server session management)
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data

  server:
    build:
      context: ../..
      dockerfile: ./apps/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - PUBLIC_URL=${PUBLIC_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CHROME_TOKEN=${CHROME_TOKEN}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - CHROME_URL=${CHROME_URL}
      - PRIVATE_KEY=${PRIVATE_KEY} 
      - PROJECT_ID=${PROJECT_ID}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=${TOKEN_URI}
      - AUTH_CERT_URL=${AUTH_CERT_URL}
      - CLIENT_CERT_URL=${CLIENT_CERT_URL}
      - UNIVERSAL_DOMAIN=${UNIVERSAL_DOMAIN}
      - REDIS_URL=${REDIS_URL}
      - REDIS_URL_CONTAINER=${REDIS_URL_CONTAINER}
      - IS_CONTAINER=true
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MAIL_FROM=${MAIL_FROM}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_KEY=${SMTP_KEY}
    depends_on:
      - redis
      - chrome

volumes:
  redis_data:
